# Generated by Django 4.1.7 on 2023-03-16 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_blogpost_article_content_article_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2023, 3, 16, 23, 24, 21, 620265, tzinfo=datetime.timezone.utc)),
        ),
    ]
