# Generated by Django 4.1.7 on 2023-04-14 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_options_alter_article_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2023, 4, 14, 14, 8, 32, 226878, tzinfo=datetime.timezone.utc)),
        ),
    ]
