# Generated by Django 4.1.7 on 2023-04-14 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('screens', models.ImageField(upload_to='projects')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2023, 4, 14, 14, 8, 32, 206558, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
