# Generated by Django 4.1.7 on 2023-04-14 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2023, 4, 14, 17, 38, 28, 177883, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='screens',
            field=models.ImageField(upload_to='static/projects'),
        ),
    ]
